version: 0.2
phases:
   install:
      runtime-versions:
         java: corretto17
   pre_build:
      commands:
      - IMAGE_REPO_URL='400839853556.dkr.ecr.eu-west-1.amazonaws.com/messaging'
      - PROJECT_NAME='messaging'
      - PROJECT_VERSION='0.0.1-SNAPSHOT'
      - echo 'Login to Amazon ECR Repository'
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $IMAGE_REPO_URL
   build:
      commands:
      - echo 'Installing dependencies'
      - mvn dependency:go-offline
      - echo 'Test'
      - mvn -Dspring.profiles.active=int clean compile test 
      - echo 'Package'
      - mvn -DskipTests=true package
      - echo 'Build a Docker image'
      - docker build -t $IMAGE_REPO_URL:$PROJECT_VERSION .
   post_build:
      commands:
      - echo 'Tag the Docker image'
      - docker tag $IMAGE_REPO_URL:$PROJECT_VERSION $IMAGE_REPO_URL:latest
      - echo 'Pushing image to ECR'
      - docker push $IMAGE_REPO_URL:$PROJECT_VERSION
      - docker push $IMAGE_REPO_URL:latest
      - echo 'Writing image definitions file.'
      - printf '[{"name":$PROJECT_NAME, "imageUri":"400839853556.dkr.ecr.eu-west-1.amazonaws.com/messaging", "imageTag":"latest"}]'  > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json