apiVersion: v1
kind: Secret
metadata:
   name: messaging-secret
   namespace: deepdreams
   labels:
      app: messaging
type: Opaque
data:
   username: ZGVlcGRyZWFtcw==
   password: RGVlcGRyZWFtczIwMjI=