# Database properties
spring:
   datasource:
      url: jdbc:postgresql://52.208.79.177:5432/${spring.application.name}
      username: ${db_username}
      password: ${db_password}
      driver-class-name: org.postgresql.Driver
      hikari:
         maximum-pool-size: 2
         connection-timeout: 30000
         idle-timeout: 30000
         minimum-idle: 1
# Application config
subscriber:
   topic_subscriber_created: arn:aws:sns:eu-west-1:400839853556:subscriber_created
         