# SES properties
ses:
   hostname: email-smtp.eu-west-1.amazonaws.com
   port: 587
   secret: ses-credentials-prod

adminsys:
   baseUrl: https://adminsys.cloud
   offerSelectionUrl: /subscription/select-offer
   
messaging:
   defaultPassword:
      secretname: default-user-password
      
billing:
   fetchBillByIdUrl: http://alb-1601743346.eu-west-1.elb.amazonaws.com:8026/api/billing/v1/id/{id}
   queueBillCreatedUrl: https://sqs.eu-west-1.amazonaws.com/400839853556/bill-created-messaging

subscriber:
   fetchSubscriberByIdUrl: http://alb-1601743346.eu-west-1.elb.amazonaws.com:8028/api/subscriber/v1/id/{id}
   queueSubscriberCreatedUrl: https://sqs.eu-west-1.amazonaws.com/400839853556/subscriber-created-messaging
   queueSubscriberSuspendedUrl: https://sqs.eu-west-1.amazonaws.com/400839853556/subscriber-suspended-messaging

subscription:
   fetchSubscriptionByIdUrl: http://alb-1601743346.eu-west-1.elb.amazonaws.com:8024/api/subscription/v1/id/{id}
   fetchByAppAndSubscriberUrl: http://alb-1601743346.eu-west-1.elb.amazonaws.com:8028/api/subscriber/v1/application/{applicationId}/subscriber/{subscriberId}
   queueSubscriptionCreatedUrl: https://sqs.eu-west-1.amazonaws.com/400839853556/subscription-created-messaging

# Logging
logging:
   logstash:
      group-name: deepdreams/${spring.application.name}
      region: ${aws.region}
   level:
      root: INFO
      org.springframework: ERROR
      org.apache: ERROR
      tech.deepdreams: INFO
      org.postgresql: ERROR