# Database properties
database:
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://54.74.248.146:5432/${spring.application.name}?sslmode=require&ssl=true
   hostname: 54.74.248.146
   port: 5432
   name: ${spring.application.name}
   username: deepdreams
   secret: postgre-credentials-prod
   schema: management
   initial-size: 1
   max-size: 5
   max-lifetime: 1800000
   idle-timeout: 600000
   
ses:
   hostname: email-smtp.eu-west-1.amazonaws.com
   port: 587
   secret: ses-credentials-prod
   
app:
   base_url: https://salari.cloud
   offer_selection_url: /subscription/select-offer
   

# AWS properties
messaging:
   queue_subscriber_created_url: https://sqs.eu-west-1.amazonaws.com/400839853556/subscriber-created-messaging

# Logging
logging:
   logstash:
      group-name: deepdreams/${spring.application.name}
      region: ${aws.region}
   level:
      root: INFO
      org.springframework: ERROR
      org.apache: ERROR
      tech.deepdreams: INFO
      org.postgresql: ERROR