# Database properties
spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/${spring.application.name}
      username: ${db_username}
      password: ${db_password}
      driver-class-name: org.postgresql.Driver
      hikari:
         maximum-pool-size: 2
         connection-timeout: 30000
         idle-timeout: 30000
         minimum-idle: 1

# AWS properties
messaging:
   queue_subscriber_created_url: https://sqs.eu-west-1.amazonaws.com/400839853556/subscriber-created-messaging

# Logging
logging:
   file:
      name: ${spring.application.name}.log
   level:
      root: INFO
      org.springframework: ERROR
      tech.deepdreams: INFO
      org.apache: ERROR