# Database properties
database:
   url: jdbc:postgresql://localhost:5432/${spring.application.name}?sslmode=require&ssl=true
   hostname: 54.74.248.146
   port: 5432
   name: ${spring.application.name}
   username: postgres
   secret: postgre-credentials-dev
   schema: management
   initial-size: 1
   max-size: 1
   max-lifetime: 1800000

# AWS properties
messaging:
   queue_subscriber_created_url: https://sqs.eu-west-1.amazonaws.com/400839853556/subscriber-created-messaging

# Logging
logging:
   file:
      name: ${spring.application.name}.log
   level:
      root: INFO
      org.springframework: ERROR
      tech.deepdreams: INFO
      org.apache: ERROR