# Database properties
database:
   url: jdbc:postgresql://localhost:5432/${spring.application.name}
   driver-class-name: org.postgresql.Driver
   hostname: localhost
   port: 5432
   name: ${spring.application.name}
   username: deepdreams
   schema: management
   dialect: org.hibernate.dialect.PostgreSQLDialect
   initial-size: 1
   max-size: 3
   max-lifetime: 1800000

# AWS properties
messaging:
   queue_subscriber_created_url: https://sqs.eu-west-1.amazonaws.com/400839853556/subscriber-created-messaging

# Logging
logging:
   file:
      name: ${spring.application.name}.log
   level:
      root: INFO
      org.springframework: ERROR
      tech.deepdreams: INFO
      org.apache: ERROR