spring:
   datasource:
      url: jdbc:postgresql://terraform-20230523104252789600000001.c0fg0k3pvlnz.eu-west-1.rds.amazonaws.com:5432/messaging?currentSchema=management
      username: ${db_username}
      password: ${db_password}
      jpa:
         properties: 
            hibernate:
               dialect: org.hibernate.dialect.PostgreSQLDialect
      hikari:
         maximum-pool-size: 5
         connection-timeout: 30000
         idle-timeout: 30000
         minimum-idle: 1

# AWS properties
messaging:
   queue_subscriber_created_url: https://sqs.eu-west-1.amazonaws.com/400839853556/subscriber-created-messaging

# Logging
logging:
   logstash:
      group-name: deepdreams/${spring.application.name}

      region: ${aws.region}
   level:
      root: INFO
      org.springframework: ERROR
      org.apache: ERROR
      tech.deepdreams: INFO