spring:
   config:
      import: aws-secretsmanager:postgre-credentials-prod
   datasource:
      url: jdbc:postgresql://54.74.248.146:5432/${spring.application.name}?ssl=true&sslmode=require&currentSchema=management
      username: deepdreams
      password: ${password}
      jpa:
         properties:
            hibernate:
               dialect: org.hibernate.dialect.PostgreSQLDialect
      hikari:
         maximum-pool-size: 5
         connection-timeout: 30000
         idle-timeout: 30000
         minimum-idle: 1

# AWS properties
messaging:
   queue_subscriber_created_url: https://sqs.eu-west-1.amazonaws.com/400839853556/subscriber-created-messaging

# Logging
logging:
   logstash:
      group-name: deepdreams/${spring.application.name}

      region: ${aws.region}
   level:
      root: INFO
      org.springframework: ERROR
      org.apache: ERROR
      tech.deepdreams: INFO