spring:
   aws:
      xray:
         enabled: true

# Database properties
database:
   url: jdbc:postgresql://52.208.79.177:5432/${spring.application.name}
   driver-class-name: org.postgresql.Driver
   hostname: 52.208.79.177
   port: 5432
   name: ${spring.application.name}
   username: deepdreams
   schema: management
   dialect: org.hibernate.dialect.PostgreSQL13Dialect
   initial-size: 3
   max-size: 10
   max-lifetime: 1000

# AWS properties
messaging:
   queue_subscriber_created_url: https://sqs.eu-west-1.amazonaws.com/400839853556/subscriber-created-messaging

# Logging
logging:
   logstash:
      group-name: deepdreams/${spring.application.name}
      region: ${aws.region}
   level:
      root: INFO
      org.springframework: ERROR
      org.apache: ERROR
      tech.deepdreams: INFO