# AWS properties
messaging:
   queueSubscriberCreatedUrl: ddd

# Database properties
database:
   hostname: localhost
   url: jdbc:postgresql://localhost:5432/${spring.application.name}
   username: deepdreams
   secret: postgres-credentials-dev
   schema: management
   initial-size: 3
   max-size: 10
   max-lifetime: 1000


# Logging
logging:
   file:
      name: ${spring.application.name}.log
   level:
      root: INFO
      org.springframework: ERROR
      tech.deepdreams: INFO
      org.apache: ERROR