openapi: 3.0.0
info:
   title: Messaging API
   description: Messaging API specification
   termsOfService: https://deepdreams.tech/terms-of-service
   contact:
      email: deepdreamapps@gmail.com
   license:
      name: Apache 2.0
      url: https://www.deepdreams.tech/licenses/LICENSE-1.0.html
   version: 0.0.1-SNAPSHOT

servers:
-  url: http://localhost:8022

paths:

   /api/subscriber/v1/id/{id}:
      get:
         summary: Get subscriber by id
         x-amazon-apigateway-cache:
            ttlInSeconds: 300
            cachingEnabled: true
         parameters:
         -  name: id
            in: path
            required: true
            schema:
               type: integer
               format: int64
         responses:
            200:
               description: Successful operation
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/ReminderEmail'
components:
   schemas:
      ReminderEmail:
         type: object
         properties:
            id:
               type: integer
               format: int64
            eventId:
               type: integer
               format: int64
            eventType:
               type: string
            timestamp:
               type: string
               format: date-time
            subject:
               type: string
            content:
               type: string
            sender:
               type: string
            recipient:
               type: string
            sent:
               type: boolean
      Message:
         type: object
         properties:
            id:
               type: integer
               format: int64
            eventId:
               type: integer
               format: int64
            eventType:
               type: string
            timestamp:
               type: string
               format: date-time
      Subscription:
         $ref: 'https://deepdreams-openapi.s3.eu-west-1.amazonaws.com/subscription/openapi.yml#/components/schemas/Subscription'
     