CREATE SCHEMA IF NOT EXISTS messaging ;

CREATE TABLE IF NOT EXISTS management.reminder_email 
(
	id bigint generated by default as identity,
	event_type varchar(100) not null,
	event_id bigint not null,
	timestamp  timestamp with time zone not null,
	subscriber_id bigint not null,
	subject varchar(255) not null,
	sender varchar(100) not null,
	recipient varchar(100) not null,
	content text not null,
	sent boolean not null,
	primary key (id)
) ;

ALTER SEQUENCE management.reminder_email_id_seq RESTART WITH 1000000000 ;

CREATE INDEX reminder_email__sent ON management.reminder_email (sent) ;
CREATE INDEX reminder_email__event_type_event_id ON management.reminder_email (event_type, event_id) ;

